version: '2'
services:
  docker-mysql:
    image: mysql:5.6.33
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ~/Documents/docker-volumes/mysql:/var/lib/mysql
    ports:
        - "6033:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  lister-backend:
    depends_on:
      - docker-mysql
    image: alannesta/lister-backend:0.3.0
    links:
      - docker-mysql
    ports:
      - "4302:4302"
    restart: always
    environment:
      MYSQL_HOST: docker-mysql
