version: '2'
services:
  docker-mysql:
    image: mysql:5.6.33
    volumes:
      - /Users/sijin.cao/Documents/docker-volume/mysql-dump:/docker-entrypoint-initdb.d
      - /Users/sijin.cao/Documents/docker-volume/mysql:/var/lib/mysql
    ports:
        - "6033:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  lister-backend:
    depends_on:
      - docker-mysql
    image: lister-backend:0.1.0
    links:
      - docker-mysql
    ports:
      - "4302:4302"
    restart: always
    environment:
      MYSQL_HOST: docker-mysql
